# Generated by Django 5.0.6 on 2024-06-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descreption', models.TextField(max_length=200)),
                ('product_type', models.IntegerField(choices=[(1, 'Lcds'), (2, 'Parts'), (3, 'Cases'), (4, 'Screen Protector'), (5, 'Cables'), (6, 'Charger'), (7, 'Vapes'), (8, 'Speaker'), (9, 'Headphone'), (10, 'Handsfree'), (11, 'Laptop Parts'), (12, 'Heater'), (13, 'Fan'), (14, 'Extention'), (15, 'Adopter'), (16, 'Holder'), (17, 'Battery')])),
                ('brand_type', models.IntegerField(choices=[(1, 'Ang'), (2, 'Hoco'), (3, 'Baku'), (4, 'Vendens'), (5, 'Budi'), (6, 'Samsung'), (7, 'Iphone'), (8, 'Huwai'), (9, 'Moto'), (10, 'Nokia'), (11, 'Sony'), (12, 'LG')])),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=100)),
                ('qr_code', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('quality_type', models.IntegerField(choices=[(1, 'Original'), (2, 'Copy'), (3, 'Semi Copy'), (4, 'Premium'), (5, 'Semi Original'), (6, 'Pull-Out')], default=2)),
                ('description', models.CharField(max_length=400)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='store.products')),
            ],
        ),
    ]
